FROM python:3.12-slim

WORKDIR /opt/zeropatch
COPY requirements-action.txt .
RUN pip install --no-cache-dir -r requirements-action.txt
COPY app ./app

ENTRYPOINT ["python", "-m", "app.action_runner"]
